apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-project-template
  title: Go Project
  description: Create a new Go project with repo and Azure DevOps pipeline
spec:
  owner: user:default/um-e.habiba
  type: service
  parameters:
    - title: Go Project Details
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./sub-directory
        values:
          projectName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
    - id: createRepoAndInitProject
      name: Create Repo and Initialize Project
      action: publish:azure
      input:
        repoUrl: ${{ parameters.repoUrl }}
        sourcePath: ./sub-directory
        defaultBranch: main
        description: "Go project repo"
        gitAuthorName: Backstage Bot
        gitAuthorEmail: backstage-bot@zeiss.com
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: "Repo ID: ${{ steps.createRepoAndInitProject.output.repositoryId }}"
    - id: createAzurePipeline
      name: Create Azure Pipeline
      action: azure:pipeline:create
      input:
        organization: ${{ (parameters.repoUrl | parseRepoUrl)['organization'] }}
        project: ${{ (parameters.repoUrl | parseRepoUrl)['project'] }}
        folder: "webinar-test"
        name: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
        repositoryId: ${{ steps.publish.output.repositoryId }}
        repositoryName: ${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}
        yamlPath: ./azure-pipelines.yaml
  output:
    links:
      - title: Repository URL
        url: https://dev.azure.com/${{ (parameters.repoUrl | parseRepoUrl).organization }}/${{ (parameters.repoUrl | parseRepoUrl).project }}/_git/${{ (parameters.repoUrl | parseRepoUrl).repo }}
