apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-project-template
  title: Go Project
  description: Create a new Go project with repo and Azure DevOps pipeline
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:default/um-e.habiba
  type: service
  parameters:
    - title: Go Project Details
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
        owner:
          title: Owner
          type: string
          description: Owner of the service
          ui:field: OwnerPicker
          ui:widget: select
          ui:options:
            allowedKinds:
              - Group
        goVersion:
          type: string
          description: Go version
          ui:help: Select the Go version to use for the project.
        dockerRegistryServiceConnection:
          title: Docker Registry Service Connection
          type: string
          description: The service connection for the Docker registry.
        imageRepository:
          title: Image Repository
          type: string
          description: The repository name for the Docker image.
        containerRegistry:
          title: Container Registry
          type: string
          description: The container registry URL.
  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./sub-directory
        values:
          projectName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
          owner: ${{ parameters.owner }}
          goVersion: ${{ parameters.goVersion }}
          dockerRegistryServiceConnection: ${{ parameters.dockerRegistryServiceConnection }}
          imageRepository: ${{ parameters.imageRepository }}
          containerRegistry: ${{ parameters.containerRegistry }}
          imageTag: ${{ parameters.imageTag }}
    - id: createRepoAndInitProject
      name: Create Repo and Initialize Project
      action: publish:azure
      input:
        repoUrl: ${{ parameters.repoUrl }}
        sourcePath: ./sub-directory
        defaultBranch: main
        description: "Go project repo"
        gitAuthorName: Backstage Bot
        gitAuthorEmail: backstage-bot@zeiss.com
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.createRepoAndInitProject.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: "Repo ID: ${{ steps.createRepoAndInitProject.output.repositoryId }}"
    - id: createAzurePipeline
      name: Create Azure Pipeline
      action: azure:pipeline:create
      input:
        organization: ${{ (parameters.repoUrl | parseRepoUrl)['organization'] }}
        project: ${{ (parameters.repoUrl | parseRepoUrl)['project'] }}
        folder: "webinar-test"
        name: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
        repositoryId: ${{ steps.createRepoAndInitProject.output.repositoryId }}
        repositoryName: ${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}
        yamlPath: ./azure-pipelines.yaml
    
  output:
    links:
    - title: Pipeline URL
      url: ${{ steps.createAzurePipeline.output.pipelineUrl }}

    - title: Repository URL
      url: https://dev.azure.com/${{ (parameters.repoUrl | parseRepoUrl).organization }}/${{ (parameters.repoUrl | parseRepoUrl).project }}/_git/${{ (parameters.repoUrl | parseRepoUrl).repo }}
      
