trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    inputs:
      version: '1.24.1'
    displayName: 'Install Go'

  - script: go build ./...
    displayName: 'Build'

  - script: go test ./...
    displayName: 'Run Tests'
